### ISSUE TITLE
shortcut to retreive values from subObjects when deserialize

### ISSUE THREAD

**Issue by yannick** [tamediadigital/asdf#15]
to simply common etl behavior it should be possible to fetch data from sub objects of the input document
with a UDA. 
options i see:

- check SerializeKeysIn  for dots and try to resolve. 
- accept array
- new UDA

**Comment by 9il** [comment]
```
struct S
{
 @SuperKeys("a.b") b;
 @SuperKeys("a.c") c;
}
```
In Asdf `a` would be scanned twice. One time for `b` and one time for `c`

**Comment by yannick** [comment]
dot syntax will not work as 
 `{ "my.name": "my.value"}` is a legal document.

i would suggest that `serializationKeysIn` gets an overwrite that accepts arrays:
`@serializationKeysIn( ["a", "b"], ["a", "b2"])`

**Comment by yannick** [comment]
included in v0.0.8, see `@serializationMultiKeysIn`
