### ISSUE TITLE
describe all UDAs

### ISSUE THREAD

**Issue by yannick** [tamediadigital/asdf#28]
make a table with all UDAs 
- name
- description
- example

**Comment by 9il** [comment]
maybe docs like Phobos like docs can be better option then very big readme,  what do you think?
I can use Sebastian work for Mir, see http://docs.mir.dlang.io/latest/mir_ndslice.html

**Comment by yannick** [comment]
sure, would be nice. what do we need to do for that?

**Comment by 9il** [comment]
a branch for github.io and configuration fix. The docs would be updated automatically from travis or circle CI
