### ISSUE TITLE
parseJsonByLine should have an option to silently skip illegal/throwing records.

### ISSUE THREAD

**Issue by yannick** [tamediadigital/asdf#3]
with huge datasets/logs you might have some invalid docs which you just want to skip.

**Comment by 9il** [comment]
it skips it by default. This is shown in the example #2

**Comment by 9il** [comment]
I don't think we need a special option. If line is invalid it returns an Asdf with empty data

**Comment by 9il** [comment]
will add it to the docs

**Comment by 9il** [comment]
So we can handle it with `map` or `filter` without adding special flags
