### ISSUE TITLE
Deserialisation : Handle null type values and int into strings

### ISSUE THREAD

**Issue by llaine** [tamediadigital/asdf#41]
I wonder if it's possible to do something like this in deserialization. 

```d
struct Vector {
  int x;
  int y;
}

auto json = `[{x:"1",x:2}, {x:null, y: null},{x:1, y:2}]`;

// Throw an error here "Unexpected ASDF kind"
auto decoded = json.parseJson.deserialize!(Vector[]);
```

Would be nice if this create the struct directly with all the values.

**Comment by 9il** [comment]
You can create a type with `opCast(T:int)()` and `this(int) and use `@serializedAs!TheType`

**Comment by 9il** [comment]
```d
struct Vector {
@serializedAs!Int:
  int x;
  int y;
}

struct Int
{
/// this(int)
///opCast(T:int)()
/// and (de) serialisation methods
}
```

**Comment by llaine** [comment]
What `opCast` stand for in this situation ?

**Comment by yannick** [comment]
see http://ddili.org/ders/d.en/operator_overloading.html

**Comment by yannick** [comment]
i opened a ticket to simplify this a bit more for the end user: https://github.com/tamediadigital/asdf/issues/43

**Comment by yannick** [comment]
`@serializationFlexible` is in v0.0.10

**Comment by llaine** [comment]
Actually I still don't understand how to do it.
I'm pretty new to this language and doesn't properly know the core concept. Can you help me a bit? 

Thank's.

**Comment by 9il** [comment]
Asdf serialisation is based on compile time reflection and [user defined attributes](http://dlang.org/spec/attribute.html#uda).

```d
import asdf;

struct Vector
{
	@serializationFlexible int x;
	@serializationFlexible int y;
}

void main()
{
	auto json = `[{"x":"1","y":2},{"x":null, "y": null},{"x":1, "y":2}]`;
	auto decoded = json.deserialize!(Vector[]);
	import std.conv;
	assert(decoded == [Vector(1, 2), Vector(0, 0), Vector(1, 2)], decoded.text);
}
```
