### ISSUE TITLE
pretty printer

### ISSUE THREAD

**Issue by yannick** [tamediadigital/asdf#45]
allow pretty printing of json

**Comment by yannick** [comment]
available in v0.0.9

**Comment by dmi7ry** [comment]
I don't see any difference between `serializeToJsonPretty()` and `serializeToJson()`.
For example, it passed:

    assert(Resources.serializeToJsonPretty() == Resources.serializeToJson());

version 0.0.10

**Comment by yannick** [comment]
@dmi7ry indeed this slipped. i pushed v0.0.11

**Comment by 9il** [comment]
@dmi7ry Asdf package at `code.dlang.org` would be updated after 10 minutes.

**Comment by dmi7ry** [comment]
Thank you, guys. Now it works fine.
