### ISSUE TITLE
Why AA support is for string and enum keys only provided?

### ISSUE THREAD

**Issue by drug007** [tamediadigital/asdf#74]
Is it just lack of resources?

**Comment by yannick** [comment]
@drug007 i am unclear what you mean by that. can you make an example in code what you would expect to work?

**Comment by drug007** [comment]
I mean
```
enum E {...}; 
string[E] aa;
```
is supported but
```
string[int] aa;
```
isn't. In sources I see support for T[string] and T[K] if (is(K == enum)) only.

**Comment by 9il** [comment]
ok, i will add

**Comment by drug007** [comment]
Probably it would be better to replace `enum` constrained version of serializeValue by `isIntegral` constrain? [`serialize.d:1183`](https://github.com/tamediadigital/asdf/blob/master/source/asdf/serialization.d#L1181):
```
void serializeValue(S, T, K)(ref S serializer, auto ref T[K] value)
	if(is(K == enum))
```
by
```
void serializeValue(S, T, K)(ref S serializer, auto ref T[K] value)
	if(isIntegral!K) <--
```
?

**Comment by 9il** [comment]
enums are serialized as strings.

**Comment by drug007** [comment]
[offtopic] code.dlang.org now doesn't work, could someone to relaunch test for PR76 when the site will be online?

**Comment by 9il** [comment]
travis does not require code.dlang.org.

**Comment by 9il** [comment]
and we can merge without appveyor

**Comment by drug007** [comment]
I always (almost) try to pass all check before merging.

**Comment by drug007** [comment]
I've check my idea about replacing `enum` by `isIntegral` and should say it's a bad idea, we need both versions of `serializeValue`.

**Comment by yannick** [comment]
close?

**Comment by drug007** [comment]
I think yes
