### ISSUE TITLE
DMD v2.077.0 build failure

### ISSUE THREAD

**Issue by ArjanKn** [tamediadigital/asdf#84]
https://github.com/tamediadigital/asdf/blob/60cfd5eb3e60421be929217b61565915ff1d8b72/examples/arrays_count/source/app.d#L11

dub build -a x86_64
```
source\app.d(11,19): Error: template asdf.jsonparser.parseJsonByLine cannot deduce function from argument types !()(ByChunk, int), candidates are:
..\..\source\asdf\jsonparser.d(144,6):        asdf.jsonparser.parseJsonByLine(Flag spaces = Yes.spaces, Input)(Input input)
dmd failed with exit code 1.
```

**Comment by 9il** [comment]
Ooops, the asdf release has breaking changes, my bad!

**Comment by 9il** [comment]
It compiles in master now, but fails with runtime exception. see #85

**Comment by 9il** [comment]
Both issues are fixed in `v0.1.6`, will be in dub soon

**Comment by 9il** [comment]
Thank you for the report!

**Comment by ArjanKn** [comment]
You're welcome. Thanx for your devotion! The other example fails too btw.
Forgot to mention that.

Op 15 nov. 2017 5:58 p.m. schreef "Ilya Yaroshenko" <
notifications@github.com>:

**Comment by 9il** [comment]
> The other example fails too btw.

Thanks! will fix it tomorrow. It fails on invalid input.
