### ISSUE TITLE
Working with circular structures?

### ISSUE THREAD

**Issue by watzon** [tamediadigital/asdf#88]
I'm still somewhat new to the world of D and to this package, so I could be missing something obvious, but I don't know. I am attempting to define a structure for [this](https://core.telegram.org/bots/api#message) object. It (Message) contains references to itself, which D doesn't seem to like. I understand the reason behind it, structures can't have optional attributes and therefore If you have `Message { Message someparam; }` you end up with an infinitely large struct.

One way around this is to use pointers, so I could do `Message { Message* someparam; }` and that compiles, but if I try and use that object with asdf I get the error `none of the overloads of 'deserializeValue' are callable using argument types (Asdf, Message*)`.

So what I'm wondering here is, how can I make that structure work?

**Comment by 9il** [comment]
Could you please provide JSON example?

**Comment by yannick** [comment]
I think you need to write your own de-/ serialize methods, fetch the primary key of the child and save that within the json.

But yes please provide an example on how you would want the jaons to look like

**Comment by watzon** [comment]
Here is a very basic sample JSON structure that includes a `reply_to_message`

```json
{
    "message_id": 37435,
    "from": {
        "id": 294972954,
        "is_bot": false,
        "first_name": "."
    },
    "chat": {
        "id": -1001108586928,
        "title": "codrTalk - laef",
        "username": "codrTalkLife",
        "type": "supergroup"
    },
    "date": 1518333677,
    "reply_to_message": {
        "message_id": 37432,
        "from": {
            "id": 292857447,
            "is_bot": false,
            "first_name": "Maxi",
            "username": "Linuxer4fun"
        },
        "chat": {
            "id": -1001108586928,
            "title": "codrTalk - laef",
            "username": "codrTalkLife",
            "type": "supergroup"
        },
        "date": 1518333645,
        "text": "Too hard to understand"
    },
    "text": "noticed that actually , i guess they use some native c implementations sometimes ?"
}
```

In theory the `reply_to_message` could also have a `reply_to_message` and so on.

**Comment by yannick** [comment]
for me the structure seems rather weird. but you could try to define `reply_to_message` as `Message*` and then define the de/serialization functions for that one and parse the Asdf as Message. 

have you tried using a class instead of struct and just define it recursively? it might just work

**Comment by watzon** [comment]
I didn't think of using a class. That actually does work.
