### ISSUE TITLE
Please add examples of Asdf <-> vibe.data.json interop

### ISSUE THREAD

**Issue by denizzzka** [tamediadigital/asdf#95]

**Comment by yannick** [comment]
i'd say you should and need only to use one of them at a time. 
or can you give a little bit more context to the question?

**Comment by denizzzka** [comment]
I am just need methods for converting vibe.data.jsonJson to Asdf struct and vice versa

**Comment by yannick** [comment]
if you have a D struct you should bde able to serialize/de serialize it with both libs. 
but if you have a parsed json within a jsonJson you will either need to serialize it or convert it to a struct first. 

if that doesn't answer the question please provide an example

**Comment by denizzzka** [comment]
> if you have a D struct you should bde able to serialize/de serialize it with both libs.

I haven't struct to deserialize. It is impossibble to get JSON string from Asdf? (toString returns it byt it is escaped)

> if that doesn't answer the question please provide an example

Just trying to write `vibe.data.json.Json toVibeJson(asdf.Asdf a)` function

**Comment by yannick** [comment]
how about `vibe.data.json.parseJson( myAsdf.serializeToJson() );`
not sure why you would need that but it should work

**Comment by denizzzka** [comment]
```D
unittest
{
    struct Test
    {
        int test_val = -123;
    }

    Test t;

    string s = serializeToJson(t);
    writeln(s);

    Asdf a = asdf.Asdf(s);
    writeln(a.serializeToJson);
}
```
```
{"test_val":-123}
{"data":[5,17,0,0,0,123,34,116,101,115,116,95,118,97,108,34,58,45,49,50,51,125]}
```

serializeToJson for Asdf returns strange result

**Comment by yannick** [comment]
this makes sense to me. you tell ASDF to serialize the Asdf datastructure. 

what you probably wanted was:

```
   struct Test
    {
        int test_val = -123;
    }

    Test t;

    string s = serializeToJson(t);
    writeln(s);

    Asdf a = asdf.Asdf(s);
    writeln( cast(string) a );

```

**Comment by denizzzka** [comment]
Thanks, it works!
