### ISSUE TITLE
Please add Asdf.toString()

### ISSUE THREAD

**Issue by denizzzka** [tamediadigital/asdf#96]

**Comment by yannick** [comment]
https://github.com/tamediadigital/asdf/blob/d536b7f85d795012e492357a8e84f8a48f8b2769/source/asdf/asdf.d#L156

**Comment by denizzzka** [comment]
I am talking about `toString` without arguments

**Comment by denizzzka** [comment]
Oh, yes, the problem is solved using `to!string`
